ShiftCyclicPath
markusbaumeister/simplicial-surfaces pull request #133
Opened 2021-09-01 13:26 UTC by MeikeWeiss

Issue #101

2021-09-20 12:01 UTC, TomGoertzen requested changes
Since ShiftCyclicPath start with two tests (in paths.gi) you should also implement an NC version of this method

2021-09-20 12:07 UTC, markusbaumeister requested changes
This looks good so far. Could you please add some tests for the remaining corner cases?

2021-09-20 12:07 UTC, markusbaumeister commented on gap/Paths/paths.gd
> +DeclareOperation("ShiftCyclicPath", [IsVertexEdgePath, IsPosInt, IsPosInt]);
NC version here

2021-09-20 12:07 UTC, markusbaumeister commented on gap/Paths/paths.gi
> +                return VertexEdgePath(complex,path);
It would be nice if there was a test case for this situation.

2021-09-20 12:07 UTC, markusbaumeister commented on gap/Paths/paths.gi
> +                return EdgeFacePath(complex, Reversed( Concatenation( path{[ePos..Length(path)]}, path{[2..ePos]} ) ));
This case is also not covered.

2021-09-23 10:28 UTC, TomGoertzen approved these changes
Looks good. Thank you for the changes :)

2021-09-23 12:19 UTC, markusbaumeister approved these changes
Very nice :).

2021-09-23 12:19 UTC, merged