Updating Animating.gi
markusbaumeister/simplicial-surfaces pull request #145
Opened 2021-09-20 14:47 UTC by TomGoertzen

I create a new Method SetVertexCoordinatesNC which takes 3 argument;
Replaced IsCyclomatic by IsPosInt,
Replaced IsSimplicialSurface and IsNotEdgeRamified by IsSimplicialSurface;
And updated various descriptions

2021-09-21 09:40 UTC, markusbaumeister requested changes
Apart from one comment, this looks fine.

2021-09-21 09:40 UTC, markusbaumeister commented on gap/PolygonalComplexes/animating.gi
> +    function(coordinates, printRecord)
You need to add the surface to the argument lists.

2021-09-23 12:17 UTC, markusbaumeister approved these changes
This looks fine now :).

2021-09-23 17:03 UTC, MeikeWeiss requested changes
Looks good, but there are some merge conflicts. Can you resolve them?

2021-10-03 09:09 UTC, MeikeWeiss approved these changes

2021-10-17 10:11 UTC, merged