Changes of edge graph
markusbaumeister/simplicial-surfaces pull request #180
Opened 2021-11-29 15:03 UTC by MeikeWeiss

I thought it would make sense to have a symmetric edge digraph like for the face graph. Furthermore, there are some other minor changes.

2021-11-30 14:57 UTC, TomGoertzen requested changes

2021-11-30 14:57 UTC, TomGoertzen commented on gap/PolygonalComplexes/graphs.gd
> +#! Since the edges in Digraphs are directed but the face graph is undirected,
Shouldn't it say: "the edge graph is undirected" :)?

2021-11-30 16:24 UTC, TomGoertzen approved these changes

2021-12-01 10:13 UTC, TomGoertzen approved these changes
Looks good

2022-01-03 09:52 UTC, ReymondAkpanya requested changes
this looks fine :)

2022-01-03 10:37 UTC, MeikeWeiss commented
Thanks! Can you please approve the pull request then?

2022-01-03 10:55 UTC, ReymondAkpanya approved these changes

2022-01-03 10:56 UTC, merged