Implemented IsTurnableEdge
markusbaumeister/simplicial-surfaces pull request #181
Opened 2021-11-30 08:44 UTC by ReymondAkpanya

2021-11-30 15:18 UTC, TomGoertzen requested changes

2021-11-30 15:18 UTC, TomGoertzen commented on gap/PolygonalComplexes/properties.gi
>  #TODO Implication to IsClosedSurface
This line should come after 614 or could be deleted

2021-11-30 15:18 UTC, TomGoertzen commented on gap/PolygonalComplexes/properties.gd
> +#! <A>edge</A>, otherwise it returns <A>true</A>. The wing tips of a
Isn't this true for the janus head then?

2021-11-30 16:26 UTC, MeikeWeiss commented on gap/PolygonalComplexes/properties.gd
> +DeclareOperation( "IsTurnableEdge", [IsPolygonalComplex, IsPosInt] );
I think it has to be DeclareProperty and then you don't need the line with the return arguments.

2021-11-30 16:26 UTC, MeikeWeiss commented on gap/PolygonalComplexes/properties.gi
> +		return true;
In this way the method returns true for a boundary edge. So, there has to be a query if edge is an inner edge or not.

2021-12-06 13:03 UTC, MeikeWeiss commented on gap/PolygonalComplexes/properties.gd
> +DeclareOperation( "IsTurnableEdge", [IsPolygonalComplex, IsPosInt] );
This is a good point. But then also a method TurnableEdges and a NC-version would make sense.

2021-12-17 15:17 UTC, TomGoertzen approved these changes
Looks good :)

2022-01-04 16:04 UTC, MeikeWeiss requested changes
Looks nice!

2022-01-04 16:04 UTC, MeikeWeiss commented on gap/PolygonalComplexes/properties.gd
> +#! induced by a given edge which are not incident this edge.
Here is a "to" missing.

2022-01-04 16:04 UTC, MeikeWeiss commented on gap/PolygonalComplexes/properties.gd
> +#! The method IsTurnableEdge checks whether the given edge is a turnable edge
It would be better to write IsTurnableEdge with < A > and < \A >.

2022-01-05 11:27 UTC, MeikeWeiss approved these changes
Nice!

2022-01-21 13:35 UTC, TomGoertzen approved these changes
Looks fine now!

2022-01-21 18:20 UTC, merged