DrawSurfaceToTikz Documentation
markusbaumeister/simplicial-surfaces pull request #184
Opened 2021-12-20 09:59 UTC by MeikeWeiss

Issue #59, Issue #58 and some ToDos

2022-01-03 09:45 UTC, ReymondAkpanya requested changes

2022-01-03 09:45 UTC, ReymondAkpanya commented on gap/PolygonalComplexes/drawing.gd
> +#! We will exemplify the first two  parameters on the example of a tetrahedron. Here the tetrahedron has holes in the
there is a unnecessary blank between "two" and "parameters"

2022-01-03 09:45 UTC, ReymondAkpanya commented on gap/PolygonalComplexes/drawing.gd
> +#! For example, consider this simplicial surface:.
unnecessary dot after "surface:"

2022-01-17 10:00 UTC, ReymondAkpanya submitted a review, later dismissed

2022-01-21 13:45 UTC, TomGoertzen reviewed
Great pictures. Please take a look at my comments

2022-01-21 13:45 UTC, TomGoertzen commented on gap/PolygonalComplexes/drawing.gd
> +pr := rec( vertexColours := ["red", "blue", "green",, "pink", "black!20!yellow"] );;
You could add a line-break here

2022-01-21 13:45 UTC, TomGoertzen commented on gap/PolygonalComplexes/drawing.gd
> +pr := rec( edgeColours := [,,,,"red", "purple", "blue", "green!80!black"] );;
Also a line-break here

2022-01-21 13:45 UTC, TomGoertzen commented on gap/PolygonalComplexes/drawing.gd
> +#! <Item><E>startingFaces</E>: After drawing this list contains the first faces that were drawn from
Maybe add a comma after "After drawing"

2022-01-24 09:28 UTC, TomGoertzen approved these changes

2022-02-17 08:24 UTC, ReymondAkpanya approved these changes

2022-02-17 08:25 UTC, merged